[package]
name = "fair-launch-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.fair-launch]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.47.2"
default-features = false
