[package]
name = "multiversx-price-aggregator-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.multiversx-price-aggregator-sc]
path = ".."

[dependencies.multiversx-sc]
version = "0.47.5"

[dependencies.multiversx-sc-meta]
version = "0.47.5"
default-features = false
