[package]
name = "mvx-game-sc-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.mvx-game-sc]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.46.0"
default-features = false
