name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@ad5ce795fd3010026361d88a6c8bd3c5df987a7b
    with:
      rust-toolchain: stable
      enable-contracts-size-report: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
