name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@1ca1d800cb591b788e274743316245edd32ed3f7
    with:
      rust-toolchain: stable
      enable-contracts-size-report: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
